<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>FileService</RootNamespace>
    </PropertyGroup>

  
  
    <ItemGroup>
        <PackageReference Include="etetudyyd.framework"  />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
        <PackageReference Include="Serilog.Sinks.Seq" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" >
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\FileService.Core\FileService.Core.csproj" />
      <ProjectReference Include="..\FileService.Domain\FileService.Domain.csproj" />
      <ProjectReference Include="..\FileService.Infrastructure.Postgres\FileService.Infrastructure.Postgres.csproj" />
      <ProjectReference Include="..\FileService.Infrastructure.S3\FileService.Infrastructure.S3.csproj" />
    </ItemGroup>

  <PropertyGroup>
    <PreserveCompilationContext>true</PreserveCompilationContext>
  </PropertyGroup>

</Project>
