<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
      <PackageId>etetudyyd.FileService.Contracts</PackageId>
      <Version>0.0.1</Version>
      <Authors>etetudyyd</Authors>
      <Company>etetudyyd</Company>
      <PackageDescription>FileService.Contracts</PackageDescription>
      <RepositoryUrl>https://github.com/etetudyyd/DirectoryService</RepositoryUrl>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="etetudyyd.Core" />
      <PackageReference Include="Microsoft.AspNetCore.Http.Features" />
      <PackageReference Include="Microsoft.Extensions.Http" />
    </ItemGroup>

</Project>
