services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: reservation_service_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5454:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  seq:
    image: datalust/seq:2024.1
    container_name: seq
    restart: always
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:80
      - 5342:5341    
    volumes:
      - seq-data:/data

volumes:
  postgres-data:
  seq-data:
